name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          docker build  -t esp32-javascript:latest -f tools/Dockerfile .
          docker run -t esp32-javascript:latest bash -c '. ./tools/install-node.sh; idf.py build'
